import { createClient } from 'https://esm.sh/@supabase/supabase-js@2'
import { getStrictCorsHeaders, handleCorsPrelight } from '../_shared/security-helpers.ts'

// Lista de todas as cidades brasileiras com índices solarimétricos
// Formato: [cidade, uf, indiceSolarimetrico]
const CIDADES_DATA: [string, string, number][] = [
  // ACRE
  ["Acrelândia", "ACRE", 4.57],
  ["Assis Brasil", "ACRE", 4.55],
  ["Brasiléia", "ACRE", 4.61],
  ["Bujari", "ACRE", 4.51],
  ["Capixaba", "ACRE", 4.58],
  ["Cruzeiro do Sul", "ACRE", 4.37],
  ["Epitaciolândia", "ACRE", 4.61],
  ["Feijó", "ACRE", 4.44],
  ["Jordão", "ACRE", 4.64],
  ["Mâncio Lima", "ACRE", 4.37],
  ["Manoel Urbano", "ACRE", 4.52],
  ["Marechal Thaumaturgo", "ACRE", 4.29],
  ["Plácido de Castro", "ACRE", 4.59],
  ["Porto Acre", "ACRE", 4.51],
  ["Porto Walter", "ACRE", 4.31],
  ["Rio Branco", "ACRE", 4.54],
  ["Rodrigues Alves", "ACRE", 4.37],
  ["Santa Rosa do Purus", "ACRE", 4.43],
  ["Sena Madureira", "ACRE", 4.53],
  ["Senador Guiomard", "ACRE", 4.57],
  ["Tarauacá", "ACRE", 4.43],
  ["Xapuri", "ACRE", 4.61],
  // ALAGOAS
  ["Água Branca", "ALAGOAS", 5.58],
  ["Anadia", "ALAGOAS", 5.11],
  ["Arapiraca", "ALAGOAS", 5.33],
  ["Atalaia", "ALAGOAS", 5.03],
  ["Barra de Santo Antônio", "ALAGOAS", 5.28],
  ["Barra de São Miguel", "ALAGOAS", 5.30],
  ["Batalha", "ALAGOAS", 5.49],
  ["Belém", "ALAGOAS", 5.39],
  ["Belo Monte", "ALAGOAS", 5.51],
  ["Boca da Mata", "ALAGOAS", 5.09],
  ["Branquinha", "ALAGOAS", 5.17],
  ["Cacimbinhas", "ALAGOAS", 5.53],
  ["Cajueiro", "ALAGOAS", 5.08],
  ["Campestre", "ALAGOAS", 5.19],
  ["Campo Alegre", "ALAGOAS", 5.17],
  ["Campo Grande", "ALAGOAS", 5.16],
  ["Canapi", "ALAGOAS", 5.68],
  ["Capela", "ALAGOAS", 5.03],
  ["Carneiros", "ALAGOAS", 5.54],
  ["Chã Preta", "ALAGOAS", 5.11],
  ["Coité do Nóia", "ALAGOAS", 5.25],
  ["Colônia Leopoldina", "ALAGOAS", 5.01],
  ["Coqueiro Seco", "ALAGOAS", 5.10],
  ["Coruripe", "ALAGOAS", 5.27],
  ["Craíbas", "ALAGOAS", 5.35],
  ["Delmiro Gouveia", "ALAGOAS", 5.76],
  ["Dois Riachos", "ALAGOAS", 5.56],
  ["Estrela de Alagoas", "ALAGOAS", 5.34],
  ["Feira Grande", "ALAGOAS", 5.18],
  ["Feliz Deserto", "ALAGOAS", 5.29],
  ["Flexeiras", "ALAGOAS", 5.11],
  ["Girau do Ponciano", "ALAGOAS", 5.34],
  ["Ibateguara", "ALAGOAS", 4.96],
  ["Igaci", "ALAGOAS", 5.31],
  ["Igreja Nova", "ALAGOAS", 5.31],
  ["Inhapi", "ALAGOAS", 5.71],
  ["Jacaré dos Homens", "ALAGOAS", 5.51],
  ["Jacuípe", "ALAGOAS", 5.05],
  ["Japaratinga", "ALAGOAS", 5.20],
  ["Jaramataia", "ALAGOAS", 5.52],
  ["Jequiá da Praia", "ALAGOAS", 5.46],
  ["Joaquim Gomes", "ALAGOAS", 4.98],
  ["Jundiá", "ALAGOAS", 5.15],
  ["Junqueiro", "ALAGOAS", 5.24],
  ["Lagoa da Canoa", "ALAGOAS", 5.32],
  ["Limoeiro de Anadia", "ALAGOAS", 5.18],
  ["Maceió", "ALAGOAS", 5.26],
  ["Major Isidoro", "ALAGOAS", 5.56],
  ["Mar Vermelho", "ALAGOAS", 5.17],
  ["Maragogi", "ALAGOAS", 5.14],
  ["Maravilha", "ALAGOAS", 5.69],
  ["Marechal Deodoro", "ALAGOAS", 5.17],
  ["Maribondo", "ALAGOAS", 5.16],
  ["Mata Grande", "ALAGOAS", 5.72],
  ["Matriz de Camaragibe", "ALAGOAS", 5.04],
  ["Messias", "ALAGOAS", 5.08],
  ["Minador do Negrão", "ALAGOAS", 5.40],
  ["Monteirópolis", "ALAGOAS", 5.58],
  ["Murici", "ALAGOAS", 5.02],
  ["Novo Lino", "ALAGOAS", 4.99],
  ["Olho d'Água das Flores", "ALAGOAS", 5.57],
  ["Olho d'Água do Casado", "ALAGOAS", 5.76],
  ["Olho d'Água Grande", "ALAGOAS", 5.25],
  ["Olivença", "ALAGOAS", 5.54],
  ["Ouro Branco", "ALAGOAS", 5.71],
  ["Palestina", "ALAGOAS", 5.54],
  ["Palmeira dos Índios", "ALAGOAS", 5.31],
  ["Pão de Açúcar", "ALAGOAS", 5.64],
  ["Pariconha", "ALAGOAS", 5.73],
  ["Paripueira", "ALAGOAS", 5.23],
  ["Passo de Camaragibe", "ALAGOAS", 5.11],
  ["Paulo Jacinto", "ALAGOAS", 5.18],
  ["Penedo", "ALAGOAS", 5.38],
  ["Piaçabuçu", "ALAGOAS", 5.40],
  ["Pilar", "ALAGOAS", 5.11],
  ["Pindoba", "ALAGOAS", 5.10],
  ["Piranhas", "ALAGOAS", 5.76],
  ["Poço das Trincheiras", "ALAGOAS", 5.65],
  ["Porto Calvo", "ALAGOAS", 5.01],
  ["Porto de Pedras", "ALAGOAS", 5.12],
  ["Porto Real do Colégio", "ALAGOAS", 5.44],
  ["Quebrangulo", "ALAGOAS", 5.16],
  ["Rio Largo", "ALAGOAS", 5.09],
  ["Roteiro", "ALAGOAS", 5.22],
  ["Santa Luzia do Norte", "ALAGOAS", 5.08],
  ["Santana do Ipanema", "ALAGOAS", 5.58],
  ["Santana do Mundaú", "ALAGOAS", 5.10],
  ["São Brás", "ALAGOAS", 5.17],
  ["São José da Laje", "ALAGOAS", 5.05],
  ["São José da Tapera", "ALAGOAS", 5.62],
  ["São Luís do Quitunde", "ALAGOAS", 5.05],
  ["São Miguel dos Campos", "ALAGOAS", 5.20],
  ["São Miguel dos Milagres", "ALAGOAS", 5.14],
  ["São Sebastião", "ALAGOAS", 5.17],
  ["Satuba", "ALAGOAS", 5.08],
  ["Senador Rui Palmeira", "ALAGOAS", 5.59],
  ["Tanque d'Arca", "ALAGOAS", 5.20],
  ["Taquarana", "ALAGOAS", 5.32],
  ["Teotônio Vilela", "ALAGOAS", 5.24],
  ["Traipu", "ALAGOAS", 5.43],
  ["União dos Palmares", "ALAGOAS", 5.08],
  ["Viçosa", "ALAGOAS", 5.19],
  // AMAPÁ
  ["Amapá", "AMAPÁ", 4.95],
  ["Calçoene", "AMAPÁ", 4.87],
  ["Cutias", "AMAPÁ", 4.75],
  ["Ferreira Gomes", "AMAPÁ", 4.70],
  ["Itaubal", "AMAPÁ", 4.71],
  ["Laranjal do Jari", "AMAPÁ", 4.67],
  ["Macapá", "AMAPÁ", 4.78],
  ["Mazagão", "AMAPÁ", 4.69],
  ["Oiapoque", "AMAPÁ", 4.89],
  ["Pedra Branca do Amapari", "AMAPÁ", 4.60],
  ["Porto Grande", "AMAPÁ", 4.68],
  ["Pracuúba", "AMAPÁ", 4.86],
  ["Santana", "AMAPÁ", 4.74],
  ["Serra do Navio", "AMAPÁ", 4.59],
  ["Tartarugalzinho", "AMAPÁ", 4.76],
  ["Vitória do Jari", "AMAPÁ", 4.67],
  // AMAZONAS
  ["Alvarães", "AMAZONAS", 4.36],
  ["Amaturá", "AMAZONAS", 4.39],
  ["Anamã", "AMAZONAS", 4.44],
  ["Anori", "AMAZONAS", 4.43],
  ["Apuí", "AMAZONAS", 4.76],
  ["Atalaia do Norte", "AMAZONAS", 4.29],
  ["Autazes", "AMAZONAS", 4.52],
  ["Barcelos", "AMAZONAS", 4.55],
  ["Barreirinha", "AMAZONAS", 4.65],
  ["Benjamin Constant", "AMAZONAS", 4.30],
  ["Beruri", "AMAZONAS", 4.45],
  ["Boa Vista do Ramos", "AMAZONAS", 4.63],
  ["Boca do Acre", "AMAZONAS", 4.52],
  ["Borba", "AMAZONAS", 4.41],
  ["Caapiranga", "AMAZONAS", 4.45],
  ["Canutama", "AMAZONAS", 4.48],
  ["Carauari", "AMAZONAS", 4.41],
  ["Careiro", "AMAZONAS", 4.50],
  ["Careiro da Várzea", "AMAZONAS", 4.50],
  ["Coari", "AMAZONAS", 4.42],
  ["Codajás", "AMAZONAS", 4.43],
  ["Eirunepé", "AMAZONAS", 4.37],
  ["Envira", "AMAZONAS", 4.35],
  ["Fonte Boa", "AMAZONAS", 4.37],
  ["Guajará", "AMAZONAS", 4.34],
  ["Humaitá", "AMAZONAS", 4.57],
  ["Ipixuna", "AMAZONAS", 4.33],
  ["Iranduba", "AMAZONAS", 4.49],
  ["Itacoatiara", "AMAZONAS", 4.56],
  ["Itamarati", "AMAZONAS", 4.38],
  ["Itapiranga", "AMAZONAS", 4.59],
  ["Japurá", "AMAZONAS", 4.44],
  ["Juruá", "AMAZONAS", 4.37],
  ["Jutaí", "AMAZONAS", 4.50],
  ["Lábrea", "AMAZONAS", 4.43],
  ["Manacapuru", "AMAZONAS", 4.48],
  ["Manaquiri", "AMAZONAS", 4.49],
  ["Manaus", "AMAZONAS", 4.53],
  ["Manicoré", "AMAZONAS", 4.52],
  ["Maraã", "AMAZONAS", 4.40],
  ["Maués", "AMAZONAS", 4.60],
  ["Nhamundá", "AMAZONAS", 4.69],
  ["Nova Olinda do Norte", "AMAZONAS", 4.52],
  ["Novo Airão", "AMAZONAS", 4.52],
  ["Novo Aripuanã", "AMAZONAS", 4.57],
  ["Parintins", "AMAZONAS", 4.71],
  ["Pauini", "AMAZONAS", 4.44],
  ["Presidente Figueiredo", "AMAZONAS", 4.54],
  ["Rio Preto da Eva", "AMAZONAS", 4.54],
  ["Santa Isabel do Rio Negro", "AMAZONAS", 4.59],
  ["Santo Antônio do Içá", "AMAZONAS", 4.42],
  ["São Gabriel da Cachoeira", "AMAZONAS", 4.56],
  ["São Paulo de Olivença", "AMAZONAS", 4.36],
  ["São Sebastião do Uatumã", "AMAZONAS", 4.60],
  ["Silves", "AMAZONAS", 4.58],
  ["Tabatinga", "AMAZONAS", 4.33],
  ["Tapauá", "AMAZONAS", 4.44],
  ["Tefé", "AMAZONAS", 4.39],
  ["Tonantins", "AMAZONAS", 4.41],
  ["Uarini", "AMAZONAS", 4.37],
  ["Urucará", "AMAZONAS", 4.65],
  ["Urucurituba", "AMAZONAS", 4.61],
  // BAHIA - principais cidades
  ["Abaíra", "BAHIA", 5.55],
  ["Abaré", "BAHIA", 5.82],
  ["Acajutiba", "BAHIA", 4.88],
  ["Adustina", "BAHIA", 5.34],
  ["Água Fria", "BAHIA", 5.18],
  ["Aiquara", "BAHIA", 4.86],
  ["Alagoinhas", "BAHIA", 4.95],
  ["Alcobaça", "BAHIA", 4.85],
  ["Almadina", "BAHIA", 4.67],
  ["Amargosa", "BAHIA", 4.93],
  ["Amélia Rodrigues", "BAHIA", 5.05],
  ["América Dourada", "BAHIA", 5.69],
  ["Anagé", "BAHIA", 5.21],
  ["Andaraí", "BAHIA", 5.22],
  ["Andorinha", "BAHIA", 5.63],
  ["Angical", "BAHIA", 5.80],
  ["Anguera", "BAHIA", 5.12],
  ["Antas", "BAHIA", 5.30],
  ["Antônio Cardoso", "BAHIA", 5.12],
  ["Antônio Gonçalves", "BAHIA", 5.55],
  ["Aporá", "BAHIA", 4.93],
  ["Apuarema", "BAHIA", 4.82],
  ["Araças", "BAHIA", 4.98],
  ["Aracatu", "BAHIA", 5.38],
  ["Araci", "BAHIA", 5.27],
  ["Aramari", "BAHIA", 4.93],
  ["Arataca", "BAHIA", 4.60],
  ["Aratuípe", "BAHIA", 4.86],
  ["Aurelino Leal", "BAHIA", 4.76],
  ["Baianópolis", "BAHIA", 5.77],
  ["Baixa Grande", "BAHIA", 5.31],
  ["Banzaê", "BAHIA", 5.30],
  ["Barra", "BAHIA", 5.91],
  ["Barra da Estiva", "BAHIA", 5.38],
  ["Barra do Choça", "BAHIA", 4.95],
  ["Barra do Mendes", "BAHIA", 5.72],
  ["Barra do Rocha", "BAHIA", 4.80],
  ["Barreiras", "BAHIA", 5.71],
  ["Barro Alto", "BAHIA", 5.71],
  ["Barrocas", "BAHIA", 5.27],
  ["Belmonte", "BAHIA", 4.73],
  ["Belo Campo", "BAHIA", 5.13],
  ["Biritinga", "BAHIA", 5.09],
  ["Boa Nova", "BAHIA", 5.05],
  ["Boa Vista do Tupim", "BAHIA", 5.33],
  ["Bom Jesus da Lapa", "BAHIA", 5.90],
  ["Bom Jesus da Serra", "BAHIA", 5.02],
  ["Boninal", "BAHIA", 5.47],
  ["Bonito", "BAHIA", 5.04],
  ["Boquira", "BAHIA", 5.91],
  ["Botuporã", "BAHIA", 5.83],
  ["Brejões", "BAHIA", 4.92],
  ["Brejolândia", "BAHIA", 5.89],
  ["Brotas de Macaúbas", "BAHIA", 5.71],
  ["Brumado", "BAHIA", 5.27],
  ["Buerarema", "BAHIA", 4.66],
  ["Buritirama", "BAHIA", 5.87],
  ["Caatiba", "BAHIA", 4.88],
  ["Cabaceiras do Paraguaçu", "BAHIA", 4.94],
  ["Cachoeira", "BAHIA", 4.96],
  ["Caculé", "BAHIA", 5.42],
  ["Caém", "BAHIA", 5.47],
  ["Caetanos", "BAHIA", 5.08],
  ["Caetité", "BAHIA", 5.50],
  ["Cafarnaum", "BAHIA", 5.67],
  ["Cairu", "BAHIA", 4.81],
  ["Caldeirão Grande", "BAHIA", 5.57],
  ["Camacan", "BAHIA", 4.65],
  ["Camaçari", "BAHIA", 4.94],
  ["Camamu", "BAHIA", 4.80],
  ["Campo Alegre de Lourdes", "BAHIA", 5.87],
  ["Campo Formoso", "BAHIA", 5.59],
  ["Canápolis", "BAHIA", 5.88],
  ["Canarana", "BAHIA", 5.72],
  ["Canavieiras", "BAHIA", 4.77],
  ["Candeal", "BAHIA", 5.10],
  ["Candeias", "BAHIA", 4.93],
  ["Candiba", "BAHIA", 5.37],
  ["Cândido Sales", "BAHIA", 5.07],
  ["Cansanção", "BAHIA", 5.43],
  ["Canudos", "BAHIA", 5.50],
  ["Capela do Alto Alegre", "BAHIA", 5.23],
  ["Capim Grosso", "BAHIA", 5.45],
  ["Caraíbas", "BAHIA", 5.25],
  ["Caravelas", "BAHIA", 4.87],
  ["Cardeal da Silva", "BAHIA", 4.91],
  ["Carinhanha", "BAHIA", 5.90],
  ["Casa Nova", "BAHIA", 5.86],
  ["Castro Alves", "BAHIA", 4.99],
  ["Catolândia", "BAHIA", 5.81],
  ["Catu", "BAHIA", 4.94],
  ["Caturama", "BAHIA", 5.63],
  ["Central", "BAHIA", 5.72],
  ["Chorrochó", "BAHIA", 5.68],
  ["Cícero Dantas", "BAHIA", 5.30],
  ["Cipó", "BAHIA", 5.12],
  ["Coaraci", "BAHIA", 4.68],
  ["Cocos", "BAHIA", 5.66],
  ["Conceição da Feira", "BAHIA", 5.05],
  ["Conceição do Almeida", "BAHIA", 4.95],
  ["Conceição do Coité", "BAHIA", 5.26],
  ["Conceição do Jacuípe", "BAHIA", 5.02],
  ["Conde", "BAHIA", 4.92],
  ["Condeúba", "BAHIA", 5.28],
  ["Contendas do Sincorá", "BAHIA", 5.25],
  ["Coração de Maria", "BAHIA", 5.03],
  ["Cordeiros", "BAHIA", 5.13],
  ["Coribe", "BAHIA", 5.88],
  ["Coronel João Sá", "BAHIA", 5.41],
  ["Correntina", "BAHIA", 5.64],
  ["Cotegipe", "BAHIA", 5.86],
  ["Cravolândia", "BAHIA", 4.86],
  ["Crisópolis", "BAHIA", 5.22],
  ["Cristópolis", "BAHIA", 5.78],
  ["Cruz das Almas", "BAHIA", 4.99],
  ["Curaçá", "BAHIA", 5.77],
  ["Dário Meira", "BAHIA", 4.82],
  ["Dias d'Ávila", "BAHIA", 4.93],
  ["Dom Basílio", "BAHIA", 5.31],
  ["Dom Macedo Costa", "BAHIA", 4.97],
  ["Elísio Medrado", "BAHIA", 4.91],
  ["Encruzilhada", "BAHIA", 5.05],
  ["Entre Rios", "BAHIA", 4.90],
  ["Érico Cardoso", "BAHIA", 5.53],
  ["Esplanada", "BAHIA", 4.91],
  ["Euclides da Cunha", "BAHIA", 5.41],
  ["Eunápolis", "BAHIA", 4.81],
  ["Fátima", "BAHIA", 5.32],
  ["Feira da Mata", "BAHIA", 5.91],
  ["Feira de Santana", "BAHIA", 5.09],
  ["Filadélfia", "BAHIA", 5.54],
  ["Firmino Alves", "BAHIA", 4.79],
  ["Floresta Azul", "BAHIA", 4.71],
  ["Formosa do Rio Preto", "BAHIA", 5.69],
  ["Gandu", "BAHIA", 4.81],
  ["Gavião", "BAHIA", 5.16],
  ["Gentio do Ouro", "BAHIA", 5.81],
  ["Glória", "BAHIA", 5.64],
  ["Gongogi", "BAHIA", 4.79],
  ["Governador Mangabeira", "BAHIA", 4.99],
  ["Guajeru", "BAHIA", 5.27],
  ["Guanambi", "BAHIA", 5.48],
  ["Guaratinga", "BAHIA", 4.79],
  ["Heliópolis", "BAHIA", 5.37],
  ["Iaçu", "BAHIA", 5.21],
  ["Ibiassucê", "BAHIA", 5.50],
  ["Ibicaraí", "BAHIA", 4.69],
  ["Ibicoara", "BAHIA", 5.40],
  ["Ibicuí", "BAHIA", 4.99],
  ["Ibipeba", "BAHIA", 5.71],
  ["Ibipitanga", "BAHIA", 5.57],
  ["Ibiquera", "BAHIA", 5.38],
  ["Ibirapitanga", "BAHIA", 4.79],
  ["Ibirapuã", "BAHIA", 4.87],
  ["Ibirataia", "BAHIA", 4.80],
  ["Ibitiara", "BAHIA", 5.56],
  ["Ibititá", "BAHIA", 5.72],
  ["Ibotirama", "BAHIA", 5.88],
  ["Ichu", "BAHIA", 5.14],
  ["Igaporã", "BAHIA", 5.55],
  ["Igrapiúna", "BAHIA", 4.79],
  ["Iguaí", "BAHIA", 4.86],
  ["Ilhéus", "BAHIA", 4.73],
  ["Inhambupe", "BAHIA", 5.00],
  ["Ipecaetá", "BAHIA", 5.10],
  ["Ipiaú", "BAHIA", 4.80],
  ["Ipirá", "BAHIA", 5.20],
  ["Ipupiara", "BAHIA", 5.66],
  ["Irajuba", "BAHIA", 5.00],
  ["Iramaia", "BAHIA", 5.17],
  ["Iraquara", "BAHIA", 5.58],
  ["Irará", "BAHIA", 5.04],
  ["Irecê", "BAHIA", 5.75],
  ["Itabela", "BAHIA", 4.80],
  ["Itaberaba", "BAHIA", 5.25],
  ["Itabuna", "BAHIA", 4.70],
  ["Itacaré", "BAHIA", 4.76],
  ["Itaeté", "BAHIA", 5.23],
  ["Itagi", "BAHIA", 4.82],
  ["Itagibá", "BAHIA", 4.83],
  ["Itagimirim", "BAHIA", 4.75],
  ["Itaguaçu da Bahia", "BAHIA", 5.84],
  ["Itaju do Colônia", "BAHIA", 4.74],
  ["Itajuípe", "BAHIA", 4.70],
  ["Itamaraju", "BAHIA", 4.81],
  ["Itamari", "BAHIA", 4.79],
  ["Itambé", "BAHIA", 5.05],
  ["Itanagra", "BAHIA", 4.90],
  ["Itanhém", "BAHIA", 4.85],
  ["Itaparica", "BAHIA", 4.93],
  ["Itapé", "BAHIA", 4.74],
  ["Itapebi", "BAHIA", 4.76],
  ["Itapetinga", "BAHIA", 4.93],
  ["Itapicuru", "BAHIA", 5.17],
  ["Itapitanga", "BAHIA", 4.72],
  ["Itaquara", "BAHIA", 4.88],
  ["Itarantim", "BAHIA", 4.89],
  ["Itatim", "BAHIA", 5.11],
  ["Itiruçu", "BAHIA", 4.95],
  ["Itiúba", "BAHIA", 5.51],
  ["Itororó", "BAHIA", 4.80],
  ["Ituaçu", "BAHIA", 5.28],
  ["Ituberá", "BAHIA", 4.79],
  ["Iuiu", "BAHIA", 5.59],
  ["Jaborandi", "BAHIA", 5.65],
  ["Jacaraci", "BAHIA", 5.32],
  ["Jacobina", "BAHIA", 5.44],
  ["Jaguaquara", "BAHIA", 4.95],
  ["Jaguarari", "BAHIA", 5.59],
  ["Jaguaripe", "BAHIA", 4.86],
  ["Jandaíra", "BAHIA", 4.90],
  ["Jequié", "BAHIA", 4.98],
  ["Jeremoabo", "BAHIA", 5.29],
  ["Jiquiriçá", "BAHIA", 4.81],
  ["Jitaúna", "BAHIA", 4.88],
  ["João Dourado", "BAHIA", 5.76],
  ["Juazeiro", "BAHIA", 5.77],
  ["Jucuruçu", "BAHIA", 4.90],
  ["Jussara", "BAHIA", 5.85],
  ["Jussari", "BAHIA", 4.72],
  ["Jussiape", "BAHIA", 5.42],
  ["Lafaiete Coutinho", "BAHIA", 4.91],
  ["Lagoa Real", "BAHIA", 5.39],
  ["Laje", "BAHIA", 4.86],
  ["Lajedão", "BAHIA", 4.88],
  ["Lajedinho", "BAHIA", 5.26],
  ["Lajedo do Tabocal", "BAHIA", 5.07],
  ["Lamarão", "BAHIA", 5.12],
  ["Lapão", "BAHIA", 5.72],
  ["Lauro de Freitas", "BAHIA", 4.93],
  ["Lençóis", "BAHIA", 5.34],
  ["Licínio de Almeida", "BAHIA", 5.35],
  ["Livramento de Nossa Senhora", "BAHIA", 5.35],
  ["Luís Eduardo Magalhães", "BAHIA", 5.66],
  ["Macajuba", "BAHIA", 5.26],
  ["Macarani", "BAHIA", 4.93],
  ["Macaúbas", "BAHIA", 5.62],
  ["Macururé", "BAHIA", 5.72],
  ["Madre de Deus", "BAHIA", 4.93],
  ["Maetinga", "BAHIA", 5.18],
  ["Maiquinique", "BAHIA", 4.91],
  ["Mairi", "BAHIA", 5.38],
  ["Malhada", "BAHIA", 5.86],
  ["Malhada de Pedras", "BAHIA", 5.33],
  ["Manoel Vitorino", "BAHIA", 5.02],
  ["Mansidão", "BAHIA", 5.88],
  ["Maracás", "BAHIA", 5.06],
  ["Maragogipe", "BAHIA", 4.91],
  ["Maraú", "BAHIA", 4.79],
  ["Marcionílio Souza", "BAHIA", 5.23],
  ["Mascote", "BAHIA", 4.68],
  ["Mata de São João", "BAHIA", 4.93],
  ["Matina", "BAHIA", 5.66],
  ["Medeiros Neto", "BAHIA", 4.88],
  ["Miguel Calmon", "BAHIA", 5.37],
  ["Milagres", "BAHIA", 5.06],
  ["Mirangaba", "BAHIA", 5.59],
  ["Mirante", "BAHIA", 5.04],
  ["Monte Santo", "BAHIA", 5.40],
  ["Morpará", "BAHIA", 5.87],
  ["Morro do Chapéu", "BAHIA", 5.55],
  ["Mortugaba", "BAHIA", 5.28],
  ["Mucugê", "BAHIA", 5.43],
  ["Mucuri", "BAHIA", 4.89],
  ["Mulungu do Morro", "BAHIA", 5.64],
  ["Mundo Novo", "BAHIA", 5.47],
  ["Muniz Ferreira", "BAHIA", 4.88],
  ["Muquém de São Francisco", "BAHIA", 5.86],
  ["Muritiba", "BAHIA", 4.98],
  ["Mutuípe", "BAHIA", 4.85],
  ["Nazaré", "BAHIA", 4.88],
  ["Nilo Peçanha", "BAHIA", 4.79],
  ["Nordestina", "BAHIA", 5.37],
  ["Nova Canaã", "BAHIA", 4.88],
  ["Nova Fátima", "BAHIA", 5.16],
  ["Nova Ibiá", "BAHIA", 4.79],
  ["Nova Itarana", "BAHIA", 4.98],
  ["Nova Redenção", "BAHIA", 5.31],
  ["Nova Soure", "BAHIA", 5.17],
  ["Nova Viçosa", "BAHIA", 4.88],
  ["Novo Horizonte", "BAHIA", 5.72],
  ["Novo Triunfo", "BAHIA", 5.30],
  ["Olindina", "BAHIA", 5.09],
  ["Oliveira dos Brejinhos", "BAHIA", 5.74],
  ["Ouriçangas", "BAHIA", 4.98],
  ["Ourolândia", "BAHIA", 5.67],
  ["Palmas de Monte Alto", "BAHIA", 5.66],
  ["Palmeiras", "BAHIA", 5.44],
  ["Paramirim", "BAHIA", 5.59],
  ["Paratinga", "BAHIA", 5.84],
  ["Paripiranga", "BAHIA", 5.33],
  ["Pau Brasil", "BAHIA", 4.73],
  ["Paulo Afonso", "BAHIA", 5.60],
  ["Pé de Serra", "BAHIA", 5.19],
  ["Pedrão", "BAHIA", 4.96],
  ["Pedro Alexandre", "BAHIA", 5.41],
  ["Piatã", "BAHIA", 5.44],
  ["Pilão Arcado", "BAHIA", 5.88],
  ["Pindaí", "BAHIA", 5.56],
  ["Pindobaçu", "BAHIA", 5.50],
  ["Pintadas", "BAHIA", 5.29],
  ["Piraí do Norte", "BAHIA", 4.79],
  ["Piripá", "BAHIA", 5.18],
  ["Piritiba", "BAHIA", 5.42],
  ["Planaltino", "BAHIA", 5.00],
  ["Planalto", "BAHIA", 4.95],
  ["Poções", "BAHIA", 4.97],
  ["Pojuca", "BAHIA", 4.93],
  ["Ponto Novo", "BAHIA", 5.53],
  ["Porto Seguro", "BAHIA", 4.80],
  ["Potiraguá", "BAHIA", 4.75],
  ["Prado", "BAHIA", 4.83],
  ["Presidente Dutra", "BAHIA", 5.74],
  ["Presidente Jânio Quadros", "BAHIA", 5.22],
  ["Presidente Tancredo Neves", "BAHIA", 4.78],
  ["Queimadas", "BAHIA", 5.38],
  ["Quijingue", "BAHIA", 5.41],
  ["Quixabeira", "BAHIA", 5.53],
  ["Rafael Jambeiro", "BAHIA", 5.17],
  ["Remanso", "BAHIA", 5.87],
  ["Retirolândia", "BAHIA", 5.30],
  ["Riachão das Neves", "BAHIA", 5.78],
  ["Riachão do Jacuípe", "BAHIA", 5.23],
  ["Riacho de Santana", "BAHIA", 5.62],
  ["Ribeira do Amparo", "BAHIA", 5.20],
  ["Ribeira do Pombal", "BAHIA", 5.29],
  ["Ribeirão do Largo", "BAHIA", 5.02],
  ["Rio de Contas", "BAHIA", 5.42],
  ["Rio do Antônio", "BAHIA", 5.34],
  ["Rio do Pires", "BAHIA", 5.55],
  ["Rio Real", "BAHIA", 5.10],
  ["Rodelas", "BAHIA", 5.66],
  ["Ruy Barbosa", "BAHIA", 5.36],
  ["Salinas da Margarida", "BAHIA", 4.87],
  ["Salvador", "BAHIA", 4.93],
  ["Santa Bárbara", "BAHIA", 5.03],
  ["Santa Brígida", "BAHIA", 5.41],
  ["Santa Cruz Cabrália", "BAHIA", 4.81],
  ["Santa Cruz da Vitória", "BAHIA", 4.78],
  ["Santa Inês", "BAHIA", 4.85],
  ["Santa Luzia", "BAHIA", 4.82],
  ["Santa Maria da Vitória", "BAHIA", 5.81],
  ["Santa Rita de Cássia", "BAHIA", 5.79],
  ["Santa Teresinha", "BAHIA", 5.24],
  ["Santaluz", "BAHIA", 5.36],
  ["Santana", "BAHIA", 5.78],
  ["Santanópolis", "BAHIA", 5.03],
  ["Santo Amaro", "BAHIA", 4.95],
  ["Santo Antônio de Jesus", "BAHIA", 4.92],
  ["Santo Estêvão", "BAHIA", 5.08],
  ["São Desidério", "BAHIA", 5.75],
  ["São Domingos", "BAHIA", 5.30],
  ["São Felipe", "BAHIA", 4.95],
  ["São Félix", "BAHIA", 4.96],
  ["São Félix do Coribe", "BAHIA", 5.84],
  ["São Francisco do Conde", "BAHIA", 4.92],
  ["São Gabriel", "BAHIA", 5.72],
  ["São Gonçalo dos Campos", "BAHIA", 5.06],
  ["São José da Vitória", "BAHIA", 4.68],
  ["São José do Jacuípe", "BAHIA", 5.35],
  ["São Miguel das Matas", "BAHIA", 4.88],
  ["São Sebastião do Passé", "BAHIA", 4.93],
  ["Sapeaçu", "BAHIA", 4.94],
  ["Sátiro Dias", "BAHIA", 5.06],
  ["Saubara", "BAHIA", 4.92],
  ["Saúde", "BAHIA", 5.51],
  ["Seabra", "BAHIA", 5.50],
  ["Sebastião Laranjeiras", "BAHIA", 5.62],
  ["Senhor do Bonfim", "BAHIA", 5.57],
  ["Sento Sé", "BAHIA", 5.87],
  ["Serra do Ramalho", "BAHIA", 5.83],
  ["Serra Dourada", "BAHIA", 5.87],
  ["Serra Preta", "BAHIA", 5.13],
  ["Serrinha", "BAHIA", 5.19],
  ["Serrolândia", "BAHIA", 5.50],
  ["Simões Filho", "BAHIA", 4.93],
  ["Sítio do Mato", "BAHIA", 5.86],
  ["Sítio do Quinto", "BAHIA", 5.38],
  ["Sobradinho", "BAHIA", 5.81],
  ["Souto Soares", "BAHIA", 5.63],
  ["Tabocas do Brejo Velho", "BAHIA", 5.83],
  ["Tanhaçu", "BAHIA", 5.13],
  ["Tanque Novo", "BAHIA", 5.54],
  ["Tanquinho", "BAHIA", 5.15],
  ["Taperoá", "BAHIA", 4.79],
  ["Tapiramutá", "BAHIA", 5.49],
  ["Teixeira de Freitas", "BAHIA", 4.88],
  ["Teodoro Sampaio", "BAHIA", 5.02],
  ["Teofilândia", "BAHIA", 5.16],
  ["Teolândia", "BAHIA", 4.78],
  ["Terra Nova", "BAHIA", 5.04],
  ["Tremedal", "BAHIA", 5.10],
  ["Tucano", "BAHIA", 5.35],
  ["Uauá", "BAHIA", 5.59],
  ["Ubaíra", "BAHIA", 4.89],
  ["Ubaitaba", "BAHIA", 4.78],
  ["Ubatã", "BAHIA", 4.80],
  ["Uibaí", "BAHIA", 5.74],
  ["Umburanas", "BAHIA", 5.61],
  ["Una", "BAHIA", 4.72],
  ["Urandi", "BAHIA", 5.52],
  ["Uruçuca", "BAHIA", 4.74],
  ["Utinga", "BAHIA", 5.50],
  ["Valença", "BAHIA", 4.80],
  ["Valente", "BAHIA", 5.27],
  ["Várzea da Roça", "BAHIA", 5.43],
  ["Várzea do Poço", "BAHIA", 5.50],
  ["Várzea Nova", "BAHIA", 5.66],
  ["Varzedo", "BAHIA", 4.92],
  ["Vera Cruz", "BAHIA", 4.91],
  ["Vereda", "BAHIA", 4.98],
  ["Vitória da Conquista", "BAHIA", 5.08],
  ["Wagner", "BAHIA", 4.92],
  ["Wanderley", "BAHIA", 5.91],
  ["Wenceslau Guimarães", "BAHIA", 4.84],
  ["Xique-Xique", "BAHIA", 6.02],
  // CEARÁ - principais cidades
  ["Fortaleza", "CEARÁ", 5.51],
  ["Caucaia", "CEARÁ", 5.47],
  ["Juazeiro do Norte", "CEARÁ", 5.88],
  ["Maracanaú", "CEARÁ", 5.47],
  ["Sobral", "CEARÁ", 5.49],
  ["Crato", "CEARÁ", 5.70],
  ["Itapipoca", "CEARÁ", 5.37],
  ["Maranguape", "CEARÁ", 5.40],
  ["Iguatu", "CEARÁ", 5.78],
  ["Quixadá", "CEARÁ", 5.62],
  // DISTRITO FEDERAL
  ["Brasília", "DISTRITO FEDERAL", 5.25],
  // ESPÍRITO SANTO - principais cidades  
  ["Vitória", "ESPÍRITO SANTO", 4.96],
  ["Vila Velha", "ESPÍRITO SANTO", 5.03],
  ["Serra", "ESPÍRITO SANTO", 4.96],
  ["Cariacica", "ESPÍRITO SANTO", 4.91],
  ["Linhares", "ESPÍRITO SANTO", 4.84],
  ["Cachoeiro de Itapemirim", "ESPÍRITO SANTO", 4.88],
  ["Colatina", "ESPÍRITO SANTO", 4.92],
  ["Guarapari", "ESPÍRITO SANTO", 4.99],
  ["São Mateus", "ESPÍRITO SANTO", 4.83],
  ["Aracruz", "ESPÍRITO SANTO", 4.87],
  // GOIÁS - principais cidades
  ["Goiânia", "GOIÁS", 5.27],
  ["Aparecida de Goiânia", "GOIÁS", 5.27],
  ["Anápolis", "GOIÁS", 5.30],
  ["Rio Verde", "GOIÁS", 5.19],
  ["Luziânia", "GOIÁS", 5.31],
  ["Águas Lindas de Goiás", "GOIÁS", 5.30],
  ["Valparaíso de Goiás", "GOIÁS", 5.29],
  ["Trindade", "GOIÁS", 5.26],
  ["Formosa", "GOIÁS", 5.33],
  ["Novo Gama", "GOIÁS", 5.29],
  ["Itumbiara", "GOIÁS", 5.18],
  ["Senador Canedo", "GOIÁS", 5.26],
  ["Catalão", "GOIÁS", 5.23],
  ["Jataí", "GOIÁS", 5.12],
  ["Planaltina", "GOIÁS", 5.33],
  // MARANHÃO - principais cidades
  ["São Luís", "MARANHÃO", 5.09],
  ["Imperatriz", "MARANHÃO", 4.98],
  ["São José de Ribamar", "MARANHÃO", 5.12],
  ["Timon", "MARANHÃO", 5.62],
  ["Caxias", "MARANHÃO", 5.50],
  ["Codó", "MARANHÃO", 5.33],
  ["Paço do Lumiar", "MARANHÃO", 5.10],
  ["Açailândia", "MARANHÃO", 4.91],
  ["Bacabal", "MARANHÃO", 5.16],
  ["Balsas", "MARANHÃO", 5.45],
  // MATO GROSSO - principais cidades
  ["Cuiabá", "MATO GROSSO", 5.14],
  ["Várzea Grande", "MATO GROSSO", 5.14],
  ["Rondonópolis", "MATO GROSSO", 5.08],
  ["Sinop", "MATO GROSSO", 4.85],
  ["Tangará da Serra", "MATO GROSSO", 4.90],
  ["Cáceres", "MATO GROSSO", 4.96],
  ["Sorriso", "MATO GROSSO", 4.88],
  ["Lucas do Rio Verde", "MATO GROSSO", 4.92],
  ["Primavera do Leste", "MATO GROSSO", 5.06],
  ["Barra do Garças", "MATO GROSSO", 5.08],
  // MATO GROSSO DO SUL - principais cidades
  ["Campo Grande", "MATO GROSSO DO SUL", 5.02],
  ["Dourados", "MATO GROSSO DO SUL", 4.93],
  ["Três Lagoas", "MATO GROSSO DO SUL", 5.11],
  ["Corumbá", "MATO GROSSO DO SUL", 4.99],
  ["Ponta Porã", "MATO GROSSO DO SUL", 4.78],
  ["Naviraí", "MATO GROSSO DO SUL", 4.89],
  ["Nova Andradina", "MATO GROSSO DO SUL", 4.97],
  ["Aquidauana", "MATO GROSSO DO SUL", 4.97],
  ["Sidrolândia", "MATO GROSSO DO SUL", 4.96],
  ["Paranaíba", "MATO GROSSO DO SUL", 5.15],
  // MINAS GERAIS - principais cidades
  ["Belo Horizonte", "MINAS GERAIS", 5.17],
  ["Uberlândia", "MINAS GERAIS", 5.24],
  ["Contagem", "MINAS GERAIS", 5.13],
  ["Juiz de Fora", "MINAS GERAIS", 4.53],
  ["Betim", "MINAS GERAIS", 5.13],
  ["Montes Claros", "MINAS GERAIS", 5.66],
  ["Ribeirão das Neves", "MINAS GERAIS", 5.15],
  ["Uberaba", "MINAS GERAIS", 5.22],
  ["Governador Valadares", "MINAS GERAIS", 4.91],
  ["Ipatinga", "MINAS GERAIS", 4.89],
  ["Sete Lagoas", "MINAS GERAIS", 5.28],
  ["Divinópolis", "MINAS GERAIS", 5.09],
  ["Santa Luzia", "MINAS GERAIS", 5.17],
  ["Ibirité", "MINAS GERAIS", 5.11],
  ["Poços de Caldas", "MINAS GERAIS", 4.89],
  ["Patos de Minas", "MINAS GERAIS", 5.33],
  ["Pouso Alegre", "MINAS GERAIS", 4.80],
  ["Teófilo Otoni", "MINAS GERAIS", 5.03],
  ["Barbacena", "MINAS GERAIS", 4.74],
  ["Sabará", "MINAS GERAIS", 5.12],
  // PARÁ - principais cidades
  ["Belém", "PARÁ", 4.72],
  ["Ananindeua", "PARÁ", 4.73],
  ["Santarém", "PARÁ", 4.74],
  ["Marabá", "PARÁ", 4.83],
  ["Parauapebas", "PARÁ", 4.78],
  ["Castanhal", "PARÁ", 4.77],
  ["Abaetetuba", "PARÁ", 4.69],
  ["Cametá", "PARÁ", 4.70],
  ["Marituba", "PARÁ", 4.73],
  ["Bragança", "PARÁ", 4.84],
  // PARAÍBA - principais cidades
  ["João Pessoa", "PARAÍBA", 5.53],
  ["Campina Grande", "PARAÍBA", 5.51],
  ["Santa Rita", "PARAÍBA", 5.48],
  ["Patos", "PARAÍBA", 5.95],
  ["Bayeux", "PARAÍBA", 5.49],
  ["Sousa", "PARAÍBA", 5.96],
  ["Cabedelo", "PARAÍBA", 5.51],
  ["Cajazeiras", "PARAÍBA", 5.91],
  ["Guarabira", "PARAÍBA", 5.38],
  ["Sapé", "PARAÍBA", 5.39],
  // PARANÁ - principais cidades
  ["Curitiba", "PARANÁ", 4.25],
  ["Londrina", "PARANÁ", 4.87],
  ["Maringá", "PARANÁ", 4.91],
  ["Ponta Grossa", "PARANÁ", 4.38],
  ["Cascavel", "PARANÁ", 4.72],
  ["São José dos Pinhais", "PARANÁ", 4.26],
  ["Foz do Iguaçu", "PARANÁ", 4.78],
  ["Colombo", "PARANÁ", 4.24],
  ["Guarapuava", "PARANÁ", 4.50],
  ["Paranaguá", "PARANÁ", 4.00],
  ["Araucária", "PARANÁ", 4.27],
  ["Toledo", "PARANÁ", 4.77],
  ["Apucarana", "PARANÁ", 4.87],
  ["Pinhais", "PARANÁ", 4.25],
  ["Campo Largo", "PARANÁ", 4.31],
  // PERNAMBUCO - principais cidades
  ["Recife", "PERNAMBUCO", 5.25],
  ["Jaboatão dos Guararapes", "PERNAMBUCO", 5.23],
  ["Olinda", "PERNAMBUCO", 5.27],
  ["Caruaru", "PERNAMBUCO", 5.33],
  ["Petrolina", "PERNAMBUCO", 5.76],
  ["Paulista", "PERNAMBUCO", 5.28],
  ["Cabo de Santo Agostinho", "PERNAMBUCO", 5.21],
  ["Camaragibe", "PERNAMBUCO", 5.23],
  ["Garanhuns", "PERNAMBUCO", 5.15],
  ["Vitória de Santo Antão", "PERNAMBUCO", 5.26],
  // PIAUÍ - principais cidades
  ["Teresina", "PIAUÍ", 5.59],
  ["Parnaíba", "PIAUÍ", 5.51],
  ["Picos", "PIAUÍ", 5.83],
  ["Piripiri", "PIAUÍ", 5.58],
  ["Floriano", "PIAUÍ", 5.72],
  ["Campo Maior", "PIAUÍ", 5.62],
  ["Barras", "PIAUÍ", 5.54],
  ["União", "PIAUÍ", 5.58],
  ["Altos", "PIAUÍ", 5.53],
  ["Pedro II", "PIAUÍ", 5.62],
  // RIO DE JANEIRO - principais cidades
  ["Rio de Janeiro", "RIO DE JANEIRO", 4.68],
  ["São Gonçalo", "RIO DE JANEIRO", 4.64],
  ["Duque de Caxias", "RIO DE JANEIRO", 4.63],
  ["Nova Iguaçu", "RIO DE JANEIRO", 4.63],
  ["Niterói", "RIO DE JANEIRO", 4.67],
  ["Belford Roxo", "RIO DE JANEIRO", 4.63],
  ["São João de Meriti", "RIO DE JANEIRO", 4.63],
  ["Campos dos Goytacazes", "RIO DE JANEIRO", 4.84],
  ["Petrópolis", "RIO DE JANEIRO", 4.44],
  ["Volta Redonda", "RIO DE JANEIRO", 4.65],
  ["Magé", "RIO DE JANEIRO", 4.60],
  ["Itaboraí", "RIO DE JANEIRO", 4.64],
  ["Macaé", "RIO DE JANEIRO", 4.79],
  ["Mesquita", "RIO DE JANEIRO", 4.63],
  ["Cabo Frio", "RIO DE JANEIRO", 4.88],
  // RIO GRANDE DO NORTE - principais cidades
  ["Natal", "RIO GRANDE DO NORTE", 5.60],
  ["Mossoró", "RIO GRANDE DO NORTE", 5.80],
  ["Parnamirim", "RIO GRANDE DO NORTE", 5.58],
  ["São Gonçalo do Amarante", "RIO GRANDE DO NORTE", 5.56],
  ["Macaíba", "RIO GRANDE DO NORTE", 5.54],
  ["Ceará-Mirim", "RIO GRANDE DO NORTE", 5.56],
  ["Caicó", "RIO GRANDE DO NORTE", 5.89],
  ["Açu", "RIO GRANDE DO NORTE", 5.82],
  ["Currais Novos", "RIO GRANDE DO NORTE", 5.72],
  ["São José de Mipibu", "RIO GRANDE DO NORTE", 5.54],
  // RIO GRANDE DO SUL - principais cidades
  ["Porto Alegre", "RIO GRANDE DO SUL", 4.35],
  ["Caxias do Sul", "RIO GRANDE DO SUL", 4.41],
  ["Pelotas", "RIO GRANDE DO SUL", 4.24],
  ["Canoas", "RIO GRANDE DO SUL", 4.33],
  ["Santa Maria", "RIO GRANDE DO SUL", 4.53],
  ["Gravataí", "RIO GRANDE DO SUL", 4.34],
  ["Viamão", "RIO GRANDE DO SUL", 4.38],
  ["Novo Hamburgo", "RIO GRANDE DO SUL", 4.33],
  ["São Leopoldo", "RIO GRANDE DO SUL", 4.33],
  ["Rio Grande", "RIO GRANDE DO SUL", 4.25],
  ["Alvorada", "RIO GRANDE DO SUL", 4.35],
  ["Passo Fundo", "RIO GRANDE DO SUL", 4.56],
  ["Sapucaia do Sul", "RIO GRANDE DO SUL", 4.33],
  ["Uruguaiana", "RIO GRANDE DO SUL", 4.70],
  ["Santa Cruz do Sul", "RIO GRANDE DO SUL", 4.43],
  // RONDÔNIA - principais cidades
  ["Porto Velho", "RONDÔNIA", 4.54],
  ["Ji-Paraná", "RONDÔNIA", 4.61],
  ["Ariquemes", "RONDÔNIA", 4.56],
  ["Vilhena", "RONDÔNIA", 4.63],
  ["Cacoal", "RONDÔNIA", 4.63],
  ["Jaru", "RONDÔNIA", 4.58],
  ["Rolim de Moura", "RONDÔNIA", 4.64],
  ["Guajará-Mirim", "RONDÔNIA", 4.54],
  ["Ouro Preto do Oeste", "RONDÔNIA", 4.61],
  ["Pimenta Bueno", "RONDÔNIA", 4.65],
  // RORAIMA - principais cidades
  ["Boa Vista", "RORAIMA", 5.03],
  ["Rorainópolis", "RORAIMA", 4.66],
  ["Caracaraí", "RORAIMA", 4.78],
  ["Alto Alegre", "RORAIMA", 5.01],
  ["Mucajaí", "RORAIMA", 4.93],
  ["Cantá", "RORAIMA", 4.96],
  ["Pacaraima", "RORAIMA", 5.00],
  ["Bonfim", "RORAIMA", 5.09],
  ["Amajari", "RORAIMA", 4.98],
  ["Iracema", "RORAIMA", 4.80],
  // SANTA CATARINA - principais cidades
  ["Joinville", "SANTA CATARINA", 3.79],
  ["Florianópolis", "SANTA CATARINA", 4.13],
  ["Blumenau", "SANTA CATARINA", 3.97],
  ["São José", "SANTA CATARINA", 4.11],
  ["Chapecó", "SANTA CATARINA", 4.58],
  ["Criciúma", "SANTA CATARINA", 4.16],
  ["Itajaí", "SANTA CATARINA", 4.01],
  ["Lages", "SANTA CATARINA", 4.23],
  ["Jaraguá do Sul", "SANTA CATARINA", 3.88],
  ["Palhoça", "SANTA CATARINA", 4.12],
  ["Balneário Camboriú", "SANTA CATARINA", 4.09],
  ["Brusque", "SANTA CATARINA", 3.97],
  ["Tubarão", "SANTA CATARINA", 4.17],
  ["São Bento do Sul", "SANTA CATARINA", 3.90],
  ["Caçador", "SANTA CATARINA", 4.37],
  // SÃO PAULO - principais cidades
  ["São Paulo", "SÃO PAULO", 4.63],
  ["Guarulhos", "SÃO PAULO", 4.63],
  ["Campinas", "SÃO PAULO", 4.85],
  ["São Bernardo do Campo", "SÃO PAULO", 4.57],
  ["Santo André", "SÃO PAULO", 4.58],
  ["Osasco", "SÃO PAULO", 4.64],
  ["São José dos Campos", "SÃO PAULO", 4.72],
  ["Ribeirão Preto", "SÃO PAULO", 5.15],
  ["Sorocaba", "SÃO PAULO", 4.80],
  ["Mauá", "SÃO PAULO", 4.58],
  ["São José do Rio Preto", "SÃO PAULO", 5.18],
  ["Mogi das Cruzes", "SÃO PAULO", 4.60],
  ["Diadema", "SÃO PAULO", 4.57],
  ["Jundiaí", "SÃO PAULO", 4.79],
  ["Piracicaba", "SÃO PAULO", 4.93],
  ["Carapicuíba", "SÃO PAULO", 4.63],
  ["Bauru", "SÃO PAULO", 5.02],
  ["Itaquaquecetuba", "SÃO PAULO", 4.60],
  ["Santos", "SÃO PAULO", 4.36],
  ["São Vicente", "SÃO PAULO", 4.35],
  ["Franca", "SÃO PAULO", 5.10],
  ["Guarujá", "SÃO PAULO", 4.36],
  ["Praia Grande", "SÃO PAULO", 4.35],
  ["Taubaté", "SÃO PAULO", 4.68],
  ["Limeira", "SÃO PAULO", 4.93],
  ["Suzano", "SÃO PAULO", 4.60],
  ["Taboão da Serra", "SÃO PAULO", 4.62],
  ["Sumaré", "SÃO PAULO", 4.90],
  ["Embu das Artes", "SÃO PAULO", 4.61],
  ["Barueri", "SÃO PAULO", 4.65],
  // SERGIPE - principais cidades
  ["Aracaju", "SERGIPE", 5.27],
  ["Nossa Senhora do Socorro", "SERGIPE", 5.24],
  ["Lagarto", "SERGIPE", 5.21],
  ["Itabaiana", "SERGIPE", 5.19],
  ["São Cristóvão", "SERGIPE", 5.24],
  ["Estância", "SERGIPE", 5.17],
  ["Tobias Barreto", "SERGIPE", 5.36],
  ["Itabaianinha", "SERGIPE", 5.22],
  ["Simão Dias", "SERGIPE", 5.32],
  ["Capela", "SERGIPE", 5.16],
  // TOCANTINS - principais cidades
  ["Palmas", "TOCANTINS", 5.20],
  ["Araguaína", "TOCANTINS", 5.00],
  ["Gurupi", "TOCANTINS", 5.17],
  ["Porto Nacional", "TOCANTINS", 5.22],
  ["Paraíso do Tocantins", "TOCANTINS", 5.19],
  ["Araguatins", "TOCANTINS", 4.98],
  ["Colinas do Tocantins", "TOCANTINS", 5.02],
  ["Guaraí", "TOCANTINS", 5.08],
  ["Tocantinópolis", "TOCANTINS", 4.99],
  ["Dianópolis", "TOCANTINS", 5.31],
]

Deno.serve(async (req) => {
  const corsHeaders = getStrictCorsHeaders(req);
  
  // Handle CORS preflight requests
  if (req.method === 'OPTIONS') {
    return handleCorsPrelight(req, { mode: 'strict' });
  }

  try {
    const supabaseUrl = Deno.env.get('SUPABASE_URL')!
    const supabaseServiceKey = Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!
    
    const supabase = createClient(supabaseUrl, supabaseServiceKey)
    
    // Delete existing data
    await supabase.from('cidades').delete().neq('id', '00000000-0000-0000-0000-000000000000')
    
    // Insert in batches of 100
    const batchSize = 100
    let inserted = 0
    
    for (let i = 0; i < CIDADES_DATA.length; i += batchSize) {
      const batch = CIDADES_DATA.slice(i, i + batchSize).map(([cidade, uf, indice]) => ({
        cidade,
        uf,
        indice_solarimetrico: indice
      }))
      
      const { error } = await supabase.from('cidades').insert(batch)
      
      if (error) {
        console.error('Error inserting batch:', error)
        throw error
      }
      
      inserted += batch.length
    }
    
    return new Response(
      JSON.stringify({ 
        success: true, 
        message: `${inserted} cidades importadas com sucesso!` 
      }),
      { 
        headers: { ...corsHeaders, 'Content-Type': 'application/json' },
        status: 200 
      }
    )
  } catch (error) {
    console.error('Error:', error)
    const errorMessage = error instanceof Error ? error.message : 'Unknown error'
    return new Response(
      JSON.stringify({ error: errorMessage }),
      { 
        headers: { ...corsHeaders, 'Content-Type': 'application/json' },
        status: 500 
      }
    )
  }
})