ALTER TABLE rag_chunks ADD COLUMN IF NOT EXISTS is_active BOOLEAN DEFAULT true;
ALTER TABLE rag_chunks ADD COLUMN IF NOT EXISTS chunk_type TEXT DEFAULT 'unknown';
ALTER TABLE rag_chunks ADD COLUMN IF NOT EXISTS quality_score FLOAT DEFAULT 0.0;