-- Padrões para detecção de intenção de FECHAMENTO (Lead Quente)
-- Frases que indicam desejo de contratar/fechar negócio

INSERT INTO sofia_detection_patterns (category, pattern, pattern_type, priority, is_active, response_template) VALUES
-- Intenção clara de contratação
('hot_lead_closing', 'quero contratar', 'keyword', 100, true, NULL),
('hot_lead_closing', 'quero fechar', 'keyword', 100, true, NULL),
('hot_lead_closing', 'quero assinar', 'keyword', 100, true, NULL),
('hot_lead_closing', 'quero o contrato', 'keyword', 100, true, NULL),
('hot_lead_closing', 'quero aderir', 'keyword', 100, true, NULL),
('hot_lead_closing', 'quero participar', 'keyword', 95, true, NULL),
('hot_lead_closing', 'quero fechar negocio', 'keyword', 100, true, NULL),
('hot_lead_closing', 'quero fechar negócio', 'keyword', 100, true, NULL),
('hot_lead_closing', 'vamos fechar', 'keyword', 100, true, NULL),
('hot_lead_closing', 'vou contratar', 'keyword', 100, true, NULL),
('hot_lead_closing', 'vou assinar', 'keyword', 100, true, NULL),
('hot_lead_closing', 'vou fechar', 'keyword', 100, true, NULL),
('hot_lead_closing', 'vou aderir', 'keyword', 100, true, NULL),
('hot_lead_closing', 'fecha comigo', 'keyword', 100, true, NULL),
('hot_lead_closing', 'pode fechar', 'keyword', 100, true, NULL),
('hot_lead_closing', 'pode enviar o contrato', 'keyword', 100, true, NULL),
('hot_lead_closing', 'manda o contrato', 'keyword', 100, true, NULL),
('hot_lead_closing', 'me manda o contrato', 'keyword', 100, true, NULL),
('hot_lead_closing', 'envia o contrato', 'keyword', 100, true, NULL),
('hot_lead_closing', 'me envia o contrato', 'keyword', 100, true, NULL),
('hot_lead_closing', 'aceito a proposta', 'keyword', 100, true, NULL),
('hot_lead_closing', 'aceito a oferta', 'keyword', 100, true, NULL),
('hot_lead_closing', 'vamos nessa', 'keyword', 95, true, NULL),
('hot_lead_closing', 'to dentro', 'keyword', 95, true, NULL),
('hot_lead_closing', 'tô dentro', 'keyword', 95, true, NULL),
('hot_lead_closing', 'estou dentro', 'keyword', 95, true, NULL),
('hot_lead_closing', 'fechado', 'keyword', 90, true, NULL),
('hot_lead_closing', 'beleza vamos', 'keyword', 90, true, NULL),
('hot_lead_closing', 'bora fechar', 'keyword', 100, true, NULL),
('hot_lead_closing', 'bora assinar', 'keyword', 100, true, NULL),

-- Regex patterns para variações
('hot_lead_closing', 'quer(o|ia)\\s+(logo\\s+)?o?\\s*contrato', 'regex', 100, true, NULL),
('hot_lead_closing', 'v(ou|amos)\\s+(fechar|assinar|contratar)', 'regex', 100, true, NULL),
('hot_lead_closing', 'pode\\s+(mandar|enviar)\\s+o?\\s*contrato', 'regex', 100, true, NULL),
('hot_lead_closing', 'manda\\s+(logo\\s+)?o?\\s*contrato', 'regex', 100, true, NULL),
('hot_lead_closing', 'aceito\\s+(a\\s+)?(proposta|oferta)', 'regex', 100, true, NULL),

-- Exclusões: Padrões que NÃO são lead quente (apenas curiosidade)
('not_hot_lead_interest', 'quero conhecer', 'keyword', 100, true, NULL),
('not_hot_lead_interest', 'quero conhecer mais', 'keyword', 100, true, NULL),
('not_hot_lead_interest', 'quero saber mais', 'keyword', 100, true, NULL),
('not_hot_lead_interest', 'quero entender', 'keyword', 100, true, NULL),
('not_hot_lead_interest', 'quero entender melhor', 'keyword', 100, true, NULL),
('not_hot_lead_interest', 'quero meu desconto', 'keyword', 100, true, NULL),
('not_hot_lead_interest', 'quero ver', 'keyword', 100, true, NULL),
('not_hot_lead_interest', 'quero simular', 'keyword', 100, true, NULL),
('not_hot_lead_interest', 'quero uma proposta', 'keyword', 100, true, NULL),
('not_hot_lead_interest', 'quero a proposta', 'keyword', 100, true, NULL),
('not_hot_lead_interest', 'quero informacoes', 'keyword', 100, true, NULL),
('not_hot_lead_interest', 'quero informações', 'keyword', 100, true, NULL),
('not_hot_lead_interest', 'quer(o|ia)\\s+(saber|conhecer|entender|ver)', 'regex', 100, true, NULL),
('not_hot_lead_interest', 'como funciona', 'keyword', 100, true, NULL),
('not_hot_lead_interest', 'me explica', 'keyword', 100, true, NULL);